name: PC Virtual Games - Build

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:
    name: Build PC Virtual Games
    runs-on: windows-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Atualizar pip
        run: |
          python -m pip install --upgrade pip

      - name: Instalar dependências
        run: |
          pip install pyinstaller

      - name: Verificar Python
        run: |
          python --version
          pyinstaller --version

      - name: Criar executável
        run: |
          pyinstaller `
            --noconfirm `
            --clean `
            --onefile `
            --windowed `
            --name PCVirtualGames `
            src/main.py

      - name: Copiar configuração
        run: |
          Copy-Item config.json dist/config.json

      - name: Criar ZIP
        run: |
          Compress-Archive `
            -Path dist/PCVirtualGames.exe,dist/config.json `
            -DestinationPath PCVirtualGames-Windows.zip

      - name: Publicar build
        uses: actions/upload-artifact@v4
        with:
          name: PCVirtualGames-Windows
          path: PCVirtualGames-Windows.zip
